version: 2

models:
  - name: dim_reddit_dates
    description: "dimension table for distinct reddit dates"
    columns:
      - name: date_id
        description: "the primary key for this date dim table"
        data_tests:
          - not_null
          - unique

      - name: calendar_month
        description: "the months of a year represented as number 1 to 12 only"
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

      - name: day_of_week
        description: '{{ doc("dim_date__day_of_week") }}'
        data_tests:
          - accepted_values:
              arguments:
                values: [0, 1, 2, 3, 4, 5, 6, 7]

  - name: dim_reddit_users
    description: "dimension table for distinct reddit users"
    columns:
      - name: user_id
        description: "The primary key for this user dim table"
        data_tests:
          # this tests if the the column in table doesn't contain any nulls 
          - not_null
          - unique

  - name: dim_reddit_posts
    description: "list of all distinct posts of reddit"
    columns:
      - name: post_id
        description: "The primary key for this table"
        data_tests:
          # this tests if the the column in table doesn't contain any nulls 
          - not_null
          - unique

  - name: fct_reddit_comments
    description: "list of all distinct comments of reddit"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments: # available in v1.10.5 and higher. Older versions can set the <argument_name> as the top-level property.
            combination_of_columns:
              - post_id_full
              - comment_id_full
              - comment_parent_id_full

  