version: 2

models:
  - name: stg_reddit_posts_comments
    description: "raw reddit posts comments from s3"
    # columns:
    #   - name: post_id
    #     description: "The primary key for this table"
    #     data_tests:
    #       # this tests if the the column in table doesn't contain any nulls 
    #       - not_null

  - name: stg_reddit_posts
    description: "raw reddit posts from s3"
    columns:
      - name: post_id
        description: "The primary key for this table"
        data_tests:
          # this tests if the the column in table doesn't contain any nulls 
          - not_null