version: 2

models:
  - name: int_reddit_comment_to_reply_ratio
    description: "comment count to reply count ratio"
    columns:
      - name: cnt
        description: "count of replies and comments"
        data_tests:
          # this tests if the the column in table doesn't contain any nulls 
          - not_null

  - name: int_reddit_users
    description: "raw reddit posts from s3"
    columns:
      - name: user_id
        description: "The primary key for this table"
        data_tests:
          # this tests if the the column in table doesn't contain any nulls 
          - not_null
          - unique