version: 2

models:
  - name: int_reddit_comment_to_reply_ratio
    description: "comment count to reply count ratio"
    columns:
      - name: cnt
        description: "count of replies and comments"
        data_tests:
          # this tests if the the column in table doesn't contain any nulls 
          - not_null

  - name: int_reddit_users
    description: "list of all distinct reddit users"
    columns:
      - name: user_id
        description: "The primary key for this user dim table"
        data_tests:
          # this tests if the the column in table doesn't contain any nulls 
          - not_null
          - unique

  - name: int_reddit_dates
    description: "list of all distinct dates of reddit comments and posts"
    columns:
      - name: date_id
        description: "the primary key for this date dim table"
        data_tests:
          - not_null
          - unique

      - name: calendar_month
        description: "test if within number 1 to 12 only"
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]

      - name: day_of_week
        description: '{{ doc("day_of_week") }}'
        data_tests:
          - accepted_values:
              arguments:
                values: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]

  - name: int_reddit_posts
    description: "list of all distinct posts of reddit"
    columns:
      - name: post_id
        description: "The primary key for this table"
        data_tests:
          # this tests if the the column in table doesn't contain any nulls 
          - not_null
          - unique

  - name: int_reddit_comments
    description: "list of all distinct comments of reddit"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments: # available in v1.10.5 and higher. Older versions can set the <argument_name> as the top-level property.
            combination_of_columns:
              - post_id_full
              - comment_id_full
              - comment_parent_id_full

  