version: 2

models:
  - name: stg_stripe__payments
    description: "payments from stripe"
    columns:
      - name: payment_id
        description: "The primary key for this table"
        data_tests:
          # this tests if the the column in table doesn't contain any nulls 
          - not_null
          - unique

      - name: payment_method
        description: "payment method used"
        data_tests:
          - accepted_values:
              arguments:
                values: ["credit_card", "coupon", "bank_transfer", "gift_card"]
        